analyzer:
  errors:
    lines_longer_than_80_chars: ignore
    cascade_invocations: ignore
    eol_at_end_of_file: ignore
include: package:very_good_analysis/analysis_options.yaml
linter:
  rules:
    public_member_api_docs: false
