import 'package:camera/camera.dart';
import 'package:io_photobooth/common/butts_repository.dart';
export './params.dart';
const CameraResolution=ResolutionPreset.max;
const CameraImageFormat=ImageFormatGroup.jpeg;
const TimeoutDuration=Duration(seconds: 360);
const ShareDuration=Duration(hours: 1);
const NumRandomProps=4;
const SideIconButtonSizeLandscape = 120.0;
const SideIconButtonSizePortait = 90.0;
const InitialCharacterScale = 0.4;
const MinCharacterScale = 0.1;
//final ShareUrl = Uri.https('infinitebutts.com','/api/butts/upload');;
final AiPrompt = const bool.hasEnvironment('AI_PROMPT') ? const String.fromEnvironment('AI_PROMPT') : "A photo booth in a mystical forest";
const AiNegativePrompt = const String.fromEnvironment('AI_NEGATIVE_PROMPT');
final EnableAi = const bool.hasEnvironment('ENABLE_AI') ? const bool.fromEnvironment('ENABLE_AI') : true;
final DefaultImageType = ImageType.photo;
final AiImageType = ImageType.photo;
